// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package goods

import (
	"github.com/gogf/gf-demo-user/v2/api/goods"
)

type ControllerV1 struct{}

func NewV1() goods.IGoodsV1 {
	return &ControllerV1{}
}
